import axios from 'axios';

// Points at the real Spring Boot AI backend (com.neuroforge.controller.AiController).
// Configure VITE_AI_BASE_URL in a .env file to override for other environments.
export const aiApi = axios.create({
  baseURL: import.meta.env.VITE_AI_BASE_URL || 'http://localhost:8082/api',
});

aiApi.interceptors.request.use((config) => {
  const token = localStorage.getItem('authToken');
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

function unwrapError(err) {
  const message = err.response?.data?.message || 'AI Service is temporarily unavailable. Please try again later.';
  const wrapped = new Error(message);
  wrapped.status = err.response?.data?.status || err.response?.status;
  return wrapped;
}

async function post(path, payload) {
  try {
    const { data } = await aiApi.post(path, payload);
    return data;
  } catch (err) {
    throw unwrapError(err);
  }
}

// Every one of these maps 1:1 to an @PostMapping in AiController. None of them
// return structured data to bind to — each returns one field of raw text
// generated by the LLM (Groq / llama-3.1-8b-instant), so the caller should
// read exactly the field named in the comment and render it as text.
export const estimateStoryPoints = (payload) => post('/ai/story-points', payload); // -> { storyPoints: null, reason }
export const recommendPriority = (payload) => post('/ai/priority', payload); // -> { response }
export const generateTaskBreakdown = (payload) => post('/ai/breakdown', payload); // -> { response }
export const generateAcceptanceCriteria = (payload) => post('/ai/acceptance-criteria', payload); // -> { response }
export const enhanceTaskDescription = (payload) => post('/ai/enhance-description', payload); // -> { enhancedDescription }
export const analyzeSprint = (payload) => post('/ai/sprint-planning', payload); // -> { analysis }
export const analyzeProjectRisk = (payload) => post('/ai/risk-analysis', payload); // -> { analysis }
